### ISSUE TITLE
Auto-populate release info from CHANGELOG.md

### ISSUE THREAD

**Issue by thomaslaurenson** [TheGrayDot/mpqcli#55]
- Potentially update GitHub Action for tag release

```
- name: Extract latest changelog section
  id: changelog
  run: |
    awk '/^## /{i++} i==1{print}' CHANGELOG.md | tail -n +2 > latest_changelog.md

- name: Create GitHub Release
  uses: softprops/action-gh-release@v2
  with:
    body_path: latest_changelog.md
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
